version: '2'  
services:  

  web:
    build: .
    container_name: dz01
    tty: true
    stdin_open: true
    command: bash -c 'python manage.py makemigrations && python manage.py migrate' 
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./src:/src
      - ./src/static:/static
      - /home/dario/Docker/db.sqlite3:/db.sqlite3
    expose:
      - "8000"
    ports:
      - "8000:8000"

  db:
    image: postgres:9.6
    container_name: pz01
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: carra
      POSTGRES_USER: carra
    tty: true
    stdin_open: true
    volumes_from:
      - db-data

  db-data:
    image: postgres:9.6
    container_name: dd01
    command:
      - /bin/true
    tty: true
    stdin_open: true
    volumes:
      - /home/dario/Docker/pgsqldata:/var/lib/postgresql/data/pgdata
    stdin_open: true
