BEGIN TRANSACTION;
CREATE TABLE "rqEirq_source" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "smNaturalCode" varchar(50) NULL, "smRegStatus" varchar(50) NULL, "smWflowStatus" varchar(50) NULL, "smCreatedOn" datetime NULL, "smModifiedOn" datetime NULL, "smUUID" char(32) NOT NULL, "code" varchar(200) NULL, "typeSource" varchar(20) NULL, "responsable_id" integer NULL REFERENCES "rqEirq_responsable" ("id"), "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"), "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"), "label" varchar(200) NULL);
CREATE TABLE "rqEirq_responsable" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "smNaturalCode" varchar(50) NULL, "smRegStatus" varchar(50) NULL, "smWflowStatus" varchar(50) NULL, "smCreatedOn" datetime NULL, "smModifiedOn" datetime NULL, "smUUID" char(32) NOT NULL, "code" varchar(200) NULL, "coordonnees" varchar(200) NULL, "notes" varchar(200) NULL, "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"), "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"), "label" varchar(200) NULL);
CREATE TABLE "rqEirq_fichier" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "smNaturalCode" varchar(50) NULL, "smRegStatus" varchar(50) NULL, "smWflowStatus" varchar(50) NULL, "smCreatedOn" datetime NULL, "smModifiedOn" datetime NULL, "smUUID" char(32) NOT NULL, "code" varchar(200) NULL, "responsable_id" integer NULL REFERENCES "rqEirq_responsable" ("id"), "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"), "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"), "source_id" integer NULL REFERENCES "rqEirq_source" ("id"), "label" varchar(200) NULL);
CREATE TABLE "rqEirq_dependance" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "smNaturalCode" varchar(50) NULL, "smRegStatus" varchar(50) NULL, "smWflowStatus" varchar(50) NULL, "smCreatedOn" datetime NULL, "smModifiedOn" datetime NULL, "smUUID" char(32) NOT NULL, "smCreatedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smModifiedBy_id" integer NULL REFERENCES "auth_user" ("id"), "smOwningTeam_id" integer NULL REFERENCES "protoLib_teamhierarchy" ("id"), "smOwningUser_id" integer NULL REFERENCES "auth_user" ("id"), "fichier_id" integer NULL REFERENCES "rqEirq_fichier" ("id"), "produit_id" integer NULL REFERENCES "rqEirq_source" ("id"));
CREATE INDEX "rqEirq_source_b0755eff" ON "rqEirq_source" ("smOwningUser_id");
CREATE INDEX "rqEirq_source_5acf3455" ON "rqEirq_source" ("smOwningTeam_id");
CREATE INDEX "rqEirq_source_55b4cdd2" ON "rqEirq_source" ("smModifiedBy_id");
CREATE INDEX "rqEirq_source_2236446a" ON "rqEirq_source" ("smCreatedBy_id");
CREATE INDEX "rqEirq_source_1ba06e10" ON "rqEirq_source" ("responsable_id");
CREATE INDEX "rqEirq_responsable_b0755eff" ON "rqEirq_responsable" ("smOwningUser_id");
CREATE INDEX "rqEirq_responsable_5acf3455" ON "rqEirq_responsable" ("smOwningTeam_id");
CREATE INDEX "rqEirq_responsable_55b4cdd2" ON "rqEirq_responsable" ("smModifiedBy_id");
CREATE INDEX "rqEirq_responsable_2236446a" ON "rqEirq_responsable" ("smCreatedBy_id");
CREATE INDEX "rqEirq_fichier_b0755eff" ON "rqEirq_fichier" ("smOwningUser_id");
CREATE INDEX "rqEirq_fichier_5acf3455" ON "rqEirq_fichier" ("smOwningTeam_id");
CREATE INDEX "rqEirq_fichier_55b4cdd2" ON "rqEirq_fichier" ("smModifiedBy_id");
CREATE INDEX "rqEirq_fichier_2236446a" ON "rqEirq_fichier" ("smCreatedBy_id");
CREATE INDEX "rqEirq_fichier_1ba06e10" ON "rqEirq_fichier" ("responsable_id");
CREATE INDEX "rqEirq_fichier_0afd9202" ON "rqEirq_fichier" ("source_id");
CREATE INDEX "rqEirq_dependance_d31e77c8" ON "rqEirq_dependance" ("fichier_id");
CREATE INDEX "rqEirq_dependance_b0755eff" ON "rqEirq_dependance" ("smOwningUser_id");
CREATE INDEX "rqEirq_dependance_8eb6132c" ON "rqEirq_dependance" ("produit_id");
CREATE INDEX "rqEirq_dependance_5acf3455" ON "rqEirq_dependance" ("smOwningTeam_id");
CREATE INDEX "rqEirq_dependance_55b4cdd2" ON "rqEirq_dependance" ("smModifiedBy_id");
CREATE INDEX "rqEirq_dependance_2236446a" ON "rqEirq_dependance" ("smCreatedBy_id");
COMMIT;
