# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import uuid
import jsonfield2.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('protoLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, null=True, max_length=100)),
                ('prefix', models.CharField(blank=True, null=True, max_length=20)),
                ('graphLevel', models.IntegerField(blank=True, null=True, default=0)),
                ('grphMode', models.IntegerField(blank=True, null=True, default=0)),
                ('graphForm', models.IntegerField(blank=True, null=True, default=0)),
                ('showPrpType', models.BooleanField(default=False)),
                ('showBorder', models.BooleanField(default=False)),
                ('showFKey', models.BooleanField(default=False)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagramEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('smVersion', models.IntegerField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('diagram', models.ForeignKey(to='prototype.Diagram')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('dbName', models.CharField(blank=True, null=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, null=True, max_length=50)),
                ('modelPrefix', models.CharField(blank=True, null=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dbEngine', models.CharField(blank=True, choices=[('sqlite3', 'sqlLite3'), ('postgres', 'Postgress'), ('mysql', 'mySQL')], default='sqlite3', null=True, max_length=20)),
                ('dbName', models.CharField(blank=True, null=True, max_length=200)),
                ('dbUser', models.CharField(blank=True, null=True, max_length=200)),
                ('dbPassword', models.CharField(blank=True, null=True, max_length=200)),
                ('dbHost', models.CharField(blank=True, null=True, max_length=200)),
                ('dbPort', models.CharField(blank=True, null=True, max_length=200)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smModifiedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smOwningTeam', models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True)),
                ('smOwningUser', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200)),
                ('baseType', models.CharField(blank=True, choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], default='string', null=True, max_length=50)),
                ('prpLength', models.IntegerField(blank=True, null=True)),
                ('prpScale', models.IntegerField(blank=True, null=True)),
                ('prpDefault', models.CharField(blank=True, null=True, max_length=50)),
                ('prpChoices', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('isPrimary', models.BooleanField(default=False)),
                ('isLookUpResult', models.BooleanField(default=False)),
                ('isNullable', models.BooleanField(default=False)),
                ('isRequired', models.BooleanField(default=False)),
                ('isReadOnly', models.BooleanField(default=False)),
                ('isForeign', models.BooleanField(editable=False, default=False)),
                ('vType', models.CharField(blank=True, choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], default='string', null=True, max_length=50)),
                ('isSensitive', models.BooleanField(default=False)),
                ('isEssential', models.BooleanField(default=False)),
                ('crudType', models.CharField(blank=True, choices=[('editable', 'Default behavior'), ('readOnly', 'Never saved (rules, functions, linked, ...)'), ('insertOnly', 'Never updated (absorbed at the time of the creation field, eg shipping address'), ('updateOnly', 'Adding null or VrDefault, (fixed initial state)'), ('storeOnly', 'Never show on screen (id, json Types, etc)'), ('screenOnly', 'Calculated on the frontend')], null=True, max_length=20)),
                ('dbName', models.CharField(blank=True, null=True, max_length=200)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEquivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('description', models.TextField(blank=True, null=True)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smModifiedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smOwningTeam', models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True)),
                ('smOwningUser', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProtoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('entity', models.ForeignKey(to='prototype.Entity')),
                ('smCreatedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smModifiedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smOwningTeam', models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True)),
                ('smOwningUser', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('smNaturalCode', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smRegStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smWflowStatus', models.CharField(editable=False, blank=True, null=True, max_length=50)),
                ('smCreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('smModifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('code', models.CharField(editable=False, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('smVersion', models.IntegerField(blank=True, null=True)),
                ('metaDefinition', jsonfield2.fields.JSONField(blank=True, null=True)),
                ('entity', models.ForeignKey(related_name='prototype_set', to='prototype.Entity')),
                ('smCreatedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smModifiedBy', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
                ('smOwningTeam', models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True)),
                ('smOwningUser', models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, primary_key=True, parent_link=True, serialize=False, to='prototype.Property')),
                ('relatedName', models.CharField(blank=True, null=True, max_length=50)),
                ('baseMin', models.CharField(blank=True, null=True, max_length=50)),
                ('baseMax', models.CharField(blank=True, null=True, max_length=50)),
                ('refMin', models.CharField(blank=True, null=True, max_length=50)),
                ('refMax', models.CharField(blank=True, null=True, max_length=50)),
                ('onRefDelete', models.CharField(blank=True, choices=[('CASCADE', 'Cascade deletes; the default'), ('PROTECT', 'Prevent deletion of the referenced object by raising ProtectedError, a subclass of django.db.IntegrityError'), ('SET_NULL', 'Set the ForeignKey null; this is only possible if null is True'), ('SET_DEFAULT', 'Set the ForeignKey to its default value; a default for the ForeignKey must be set.  @function si possible'), ('DO_NOTHING', 'Use default Db constraint')], null=True, max_length=50)),
                ('typeRelation', models.CharField(blank=True, null=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('prototype.property',),
        ),
        migrations.AddField(
            model_name='propertyequivalence',
            name='sourceProperty',
            field=models.ForeignKey(blank=True, related_name='sourcePrp', to='prototype.Property', null=True),
        ),
        migrations.AddField(
            model_name='propertyequivalence',
            name='targetProperty',
            field=models.ForeignKey(blank=True, related_name='targetPrp', to='prototype.Property', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='entity',
            field=models.ForeignKey(related_name='property_set', to='prototype.Entity'),
        ),
        migrations.AddField(
            model_name='property',
            name='smCreatedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='smModifiedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='smOwningTeam',
            field=models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='smOwningUser',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='project',
            field=models.ForeignKey(to='prototype.Project'),
        ),
        migrations.AddField(
            model_name='model',
            name='smCreatedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='smModifiedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='smOwningTeam',
            field=models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='smOwningUser',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='smTags',
            field=taggit.managers.TaggableManager(blank=True, to='taggit.Tag', verbose_name='Tags', through='taggit.TaggedItem', help_text='A comma-separated list of tags.'),
        ),
        migrations.AddField(
            model_name='entity',
            name='model',
            field=models.ForeignKey(related_name='entity_set', to='prototype.Model'),
        ),
        migrations.AddField(
            model_name='entity',
            name='smCreatedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='smModifiedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='smOwningTeam',
            field=models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='smOwningUser',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='entity',
            field=models.ForeignKey(to='prototype.Entity'),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smCreatedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smModifiedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smOwningTeam',
            field=models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagramentity',
            name='smOwningUser',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='project',
            field=models.ForeignKey(to='prototype.Project'),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smCreatedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smModifiedBy',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smOwningTeam',
            field=models.ForeignKey(blank=True, related_name='+', to='protoLib.TeamHierarchy', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='smOwningUser',
            field=models.ForeignKey(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='refEntity',
            field=models.ForeignKey(null=True, related_name='refEntity_set', to='prototype.Entity'),
        ),
        migrations.AlterUniqueTogether(
            name='prototype',
            unique_together=set([('entity', 'code', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='propertyequivalence',
            unique_together=set([('sourceProperty', 'targetProperty', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('entity', 'code', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('code', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('project', 'code', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('model', 'code', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='diagramentity',
            unique_together=set([('diagram', 'entity', 'smOwningTeam')]),
        ),
        migrations.AlterUniqueTogether(
            name='diagram',
            unique_together=set([('project', 'code', 'smOwningTeam')]),
        ),
    ]
