CREATE TABLE "TypeSource" (
    typeSource  = models.CharField(blank= True, null= True)
    nomSource = models.CharField(blank= True, null= True)
    nomFichier    = models.CharField(blank= True, null= True)

    Responsable    = models.CharField(blank= True, null= True)

    piloteSys = models.CharField(blank= True, null= True)
    
    emplacementDonnees    = models.CharField(blank= True, null= True)
    frequence = models.CharField(blank= True, null= True)
    reception = models.CharField(blank= True, null= True)
    chargementPCDC    = models.CharField(blank= True, null= True)
    oWB   = models.CharField(blank= True, null= True)
    sQL   = models.CharField(blank= True, null= True)
    sQLLOADER = models.CharField(blank= True, null= True)
    pointNET  = models.CharField(blank= True, null= True)
    m8    = models.CharField(blank= True, null= True)
    mAILX = models.CharField(blank= True, null= True)
    cobol = models.CharField(blank= True, null= True)
    sAS   = models.CharField(blank= True, null= True)
    kSH   = models.CharField(blank= True, null= True)
    vB6   = models.CharField(blank= True, null= True)
    identificationD1  = models.CharField(blank= True, null= True)
    scenario  = models.CharField(blank= True, null= True)
    codeUntTraitement = models.CharField(blank= True, null= True)
    chaineExtraction  = models.CharField(blank= True, null= True)
    chaineNettoyage   = models.CharField(blank= True, null= True)
    chaineChargement  = models.CharField(blank= True, null= True)
    typeExploitation  = models.CharField(blank= True, null= True)
    dGU   = models.CharField(blank= True, null= True)
    vPA   = models.CharField(blank= True, null= True)
    documentation = models.CharField(blank= True, null= True)
    modeleDonnees = models.CharField(blank= True, null= True)
    metadonnees   = models.CharField(blank= True, null= True)
    formulaire    = models.CharField(blank= True, null= True)
    signal    = models.CharField(blank= True, null= True)
    ficheCognos   = models.CharField(blank= True, null= True)
    eA_CollecteAutorisee  = models.CharField(blank= True, null= True)
    eA_CollecterMemeTemps = models.CharField(blank= True, null= True)
    eA_PartiraZero    = models.CharField(blank= True, null= True)
    notes = models.CharField(blank= True, null= True)

    

    ALGO  = models.CharField(blank= True, null= True)
    Avantagelogement  = models.CharField(blank= True, null= True)
    AvantagelogementHQ    = models.CharField(blank= True, null= True)
    BNR   = models.CharField(blank= True, null= True)
    CoteISA   = models.CharField(blank= True, null= True)
    CreancesFiscales  = models.CharField(blank= True, null= True)
    DerivationD2BBB   = models.CharField(blank= True, null= True)
    DerivationD2BBC   = models.CharField(blank= True, null= True)
    DivulgationVolontaire = models.CharField(blank= True, null= True)
    EnquetesSpeciales = models.CharField(blank= True, null= True)
    ExtractionMAD = models.CharField(blank= True, null= True)
    GainCapital   = models.CharField(blank= True, null= True)
    IGIF  = models.CharField(blank= True, null= True)
    IGSEVIR   = models.CharField(blank= True, null= True)
    IndustrieVetement = models.CharField(blank= True, null= True)
    IR_NP = models.CharField(blank= True, null= True)
    IR_SD = models.CharField(blank= True, null= True)
    IR_Societe    = models.CharField(blank= True, null= True)
    IR_selectionNP    = models.CharField(blank= True, null= True)
    IR_selectionSD    = models.CharField(blank= True, null= True)
    IR_MouvementTresorerie    = models.CharField(blank= True, null= True)
    IR_CasRisqueActifs    = models.CharField(blank= True, null= True)
    IR_CasRisque_non_production   = models.CharField(blank= True, null= True)
    IR_CasRisque_sous_declaration = models.CharField(blank= True, null= True)
    Location_ImmeublesParticulier = models.CharField(blank= True, null= True)
    Location_ImmeublesSocietes    = models.CharField(blank= True, null= True)
    Nelson_Declaration_debitrice  = models.CharField(blank= True, null= True)
    PDD   = models.CharField(blank= True, null= True)
    Projet_MIRE   = models.CharField(blank= True, null= True)
    Qui_vit_la    = models.CharField(blank= True, null= True)
    RAS_TAX   = models.CharField(blank= True, null= True)
    RDPRM = models.CharField(blank= True, null= True)
    DGP_Pension_alimentaire   = models.CharField(blank= True, null= True)
    Recouvrement_alimentaire  = models.CharField(blank= True, null= True)
    ReferentielAdresses_D2    = models.CharField(blank= True, null= True)
    Referentiel_D2_ADR_REF    = models.CharField(blank= True, null= True)
    Referentiel_D2_REF_ADR_COMPL  = models.CharField(blank= True, null= True)
    Referentiel_D2_REF_ADR_DGEQ   = models.CharField(blank= True, null= True)
    Referentiel_lien_de_parente   = models.CharField(blank= True, null= True)
    Referentiel_lien_personne_entreprise  = models.CharField(blank= True, null= True)
    Releves   = models.CharField(blank= True, null= True)
    Renseignements_verificateurs  = models.CharField(blank= True, null= True)
    Resto = models.CharField(blank= True, null= True)
    DGP_Pensions_alimentaires = models.CharField(blank= True, null= True)
    Resto_Indices = models.CharField(blank= True, null= True)
    RQAP  = models.CharField(blank= True, null= True)
    SMCM  = models.CharField(blank= True, null= True)
    Statut_de_residence   = models.CharField(blank= True, null= True)
    Tableau_de_bord_Centrale_de_donnees   = models.CharField(blank= True, null= True)
    Tableau_de_bord_DGP   = models.CharField(blank= True, null= True)
    Tableau_de_bord_DGTT  = models.CharField(blank= True, null= True)
    Tableau_de_bord_Service_client    = models.CharField(blank= True, null= True)
    Taxes_percues_non_remises = models.CharField(blank= True, null= True)
    Transactions_immob_personnes_liees    = models.CharField(blank= True, null= True)
    RPSIPA    = models.CharField(blank= True, null= True)
    Cube_D3_Renseignement = models.CharField(blank= True, null= True)
    Cube_D3_Renseignements_en_erreur  = models.CharField(blank= True, null= True)
    IGALFI    = models.CharField(blank= True, null= True)
    IGSEVIR2  = models.CharField(blank= True, null= True)
    Cubes_SICAR   = models.CharField(blank= True, null= True)
    F7_DIVO   TEXT

);
