# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import jsonfield2.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protoLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtefactCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isMain', models.BooleanField(default=False)),
                ('artefact', models.ForeignKey(to='rai01ref.Artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('condition', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('containerArt', models.ForeignKey(verbose_name='Artefact', related_name='artefactcomposition_set', to='rai01ref.Artefact')),
                ('inputArt', models.ForeignKey(verbose_name='in', related_name='+', to='rai01ref.Artefact')),
                ('outputArt', models.ForeignKey(blank=True, verbose_name='out', null=True, related_name='+', to='rai01ref.Artefact')),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isMain', models.BooleanField(default=False)),
                ('artefact', models.ForeignKey(to='rai01ref.Artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ArtefactSource',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artefact', models.ForeignKey(blank=True, null=True, to='rai01ref.Artefact')),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('copyFrom', models.ForeignKey(blank=True, null=True, related_name='copy_set', to='rai01ref.Capacity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('baseType', models.CharField(max_length=50, default='string', choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], blank=True, null=True)),
                ('prpLength', models.IntegerField(blank=True, null=True)),
                ('prpScale', models.IntegerField(blank=True, null=True)),
                ('vType', models.CharField(max_length=50, default='string', choices=[('string', 'string'), ('text', 'text'), ('bool', 'bool'), ('int', 'int'), ('sequence', 'sequence'), ('decimal', 'decimal'), ('money', 'money'), ('combo', 'combo'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], blank=True, null=True)),
                ('prpDefault', models.CharField(max_length=50, null=True, blank=True)),
                ('prpChoices', models.TextField(blank=True, null=True)),
                ('isRequired', models.BooleanField(default=False)),
                ('isSensitive', models.BooleanField(default=False)),
                ('crudType', models.CharField(max_length=20, null=True, choices=[('editable', 'Default behavior'), ('readOnly', 'Never saved (rules, functions, linked, ...)'), ('insertOnly', 'Never updated (absorbed at the time of the creation field, eg shipping address'), ('updateOnly', 'Adding null or VrDefault, (fixed initial state)'), ('storeOnly', 'Never show on screen (id, json Types, etc)'), ('screenOnly', 'Calculated on the frontend')], blank=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('document', models.CharField(max_length=11, choices=[('Artefact', 'Artefact'), ('Capacity', 'Capacity'), ('Requirement', 'Requirement')])),
                ('dtype', models.CharField(max_length=200, verbose_name='DocType')),
                ('category', models.CharField(max_length=50, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArtefact',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('artefact', models.ForeignKey(to='rai01ref.Artefact')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.ForeignKey(to='rai01ref.Capacity')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('info', jsonfield2.fields.JSONField(default={})),
                ('copyFrom', models.ForeignKey(blank=True, null=True, related_name='copy_set', to='rai01ref.Requirement')),
                ('docType', models.ForeignKey(blank=True, null=True, related_name='+', to='rai01ref.DocType')),
                ('refRequirement', models.ForeignKey(blank=True, verbose_name='Parent', null=True, related_name='ref_set', to='rai01ref.Requirement')),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smRegStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smWflowStatus', models.CharField(max_length=50, editable=False, blank=True, null=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200, null=True, blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('smCreatedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='projet',
            field=models.ForeignKey(to='rai01ref.Projet'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='requirement',
            field=models.ForeignKey(to='rai01ref.Requirement'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='projet',
            field=models.ForeignKey(to='rai01ref.Projet'),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='projectcapacity',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='projet',
            field=models.ForeignKey(to='rai01ref.Projet'),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='projectartefact',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='docType',
            field=models.ForeignKey(blank=True, null=True, to='rai01ref.DocType'),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='docattribute',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacity',
            name='docType',
            field=models.ForeignKey(blank=True, null=True, related_name='+', to='rai01ref.DocType'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='refCapacity',
            field=models.ForeignKey(blank=True, verbose_name='Parent', null=True, related_name='ref_set', to='rai01ref.Capacity'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefactsource',
            name='source',
            field=models.ForeignKey(blank=True, null=True, to='rai01ref.Source'),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='requirement',
            field=models.ForeignKey(to='rai01ref.Requirement'),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='artefactrequirement',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='capacity',
            field=models.ForeignKey(to='rai01ref.Capacity'),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='artefactcapacity',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefact',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, to='rai01ref.Capacity'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='copyFrom',
            field=models.ForeignKey(blank=True, null=True, related_name='copy_set', to='rai01ref.Artefact'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='docType',
            field=models.ForeignKey(blank=True, null=True, related_name='+', to='rai01ref.DocType'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='refArtefact',
            field=models.ForeignKey(blank=True, verbose_name='Parent', null=True, related_name='ref_set', to='rai01ref.Artefact'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, to='rai01ref.Requirement'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smCreatedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smModifiedBy',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smOwningTeam',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='smOwningUser',
            field=models.ForeignKey(editable=False, blank=True, null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirement',
            unique_together=set([('projet', 'requirement')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectcapacity',
            unique_together=set([('projet', 'capacity')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectartefact',
            unique_together=set([('artefact', 'projet')]),
        ),
        migrations.AlterUniqueTogether(
            name='doctype',
            unique_together=set([('document', 'dtype')]),
        ),
        migrations.AlterUniqueTogether(
            name='docattribute',
            unique_together=set([('docType', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefactsource',
            unique_together=set([('source', 'artefact')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefactrequirement',
            unique_together=set([('artefact', 'requirement')]),
        ),
        migrations.AlterUniqueTogether(
            name='artefactcapacity',
            unique_together=set([('artefact', 'capacity')]),
        ),
    ]
