# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings
import jsonfield2.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protoLib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('code', models.CharField(max_length=200, null=True, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('fillcolor', models.CharField(max_length=200, null=True, blank=True)),
                ('gradientangle', models.CharField(max_length=200, null=True, blank=True)),
                ('color', models.CharField(max_length=200, null=True, blank=True)),
                ('graphType', models.CharField(max_length=200, null=True, blank=True)),
                ('gvParams', models.CharField(max_length=800, null=True, blank=True)),
                ('smCreatedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('list_%(class)', 'Can list available %(class)s'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanvasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('canvas', models.ForeignKey(null=True, blank=True, to='rqGraph.Canvas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200, null=True, blank=True)),
                ('label', models.CharField(max_length=200, null=True, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('labelAsNode', models.BooleanField(default=False)),
                ('hideNodes', models.BooleanField(default=False)),
                ('fillcolor', models.CharField(max_length=200, null=True, blank=True)),
                ('gradientangle', models.CharField(max_length=200, null=True, blank=True)),
                ('color', models.CharField(max_length=200, null=True, blank=True)),
                ('gvParams', models.CharField(max_length=800, null=True, blank=True)),
                ('parentCluster', models.ForeignKey(null=True, blank=True, related_name='cluster_set', to='rqGraph.Cluster')),
                ('smCreatedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('cluster', models.ForeignKey(null=True, blank=True, to='rqGraph.Cluster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200, null=True, blank=True)),
                ('label', models.CharField(max_length=200, null=True, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('url', models.CharField(max_length=800, null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdgeStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200, null=True, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('dir', models.CharField(max_length=200, null=True, blank=True)),
                ('color', models.CharField(max_length=200, null=True, blank=True)),
                ('arrowhead', models.CharField(max_length=200, null=True, blank=True)),
                ('arrowtail', models.CharField(max_length=200, null=True, blank=True)),
                ('arrowsize', models.IntegerField(null=True, blank=True)),
                ('xlabel', models.CharField(max_length=200, null=True, blank=True)),
                ('style', models.CharField(max_length=200, null=True, blank=True)),
                ('lhead', models.CharField(max_length=200, null=True, blank=True)),
                ('ltail', models.CharField(max_length=200, null=True, blank=True)),
                ('constraint', models.BooleanField(default=False)),
                ('fontname', models.CharField(max_length=200, null=True, blank=True)),
                ('fontsize', models.CharField(max_length=200, null=True, blank=True)),
                ('fontcolor', models.CharField(max_length=200, null=True, blank=True)),
                ('gvParams', models.CharField(max_length=800, null=True, blank=True)),
                ('smCreatedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200, null=True, blank=True)),
                ('label', models.CharField(max_length=200, null=True, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=800, null=True, blank=True)),
                ('rank', models.CharField(max_length=200, null=True, blank=True)),
                ('idContenttype', models.IntegerField(null=True, blank=True)),
                ('idSource', models.IntegerField(null=True, blank=True)),
                ('smCreatedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('smNaturalCode', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smRegStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smWflowStatus', models.CharField(max_length=50, null=True, editable=False, blank=True)),
                ('smCreatedOn', models.DateTimeField(null=True, auto_now_add=True)),
                ('smModifiedOn', models.DateTimeField(null=True, auto_now=True)),
                ('smUUID', models.UUIDField(editable=False, default=uuid.uuid4)),
                ('smInfo', jsonfield2.fields.JSONField(default={})),
                ('code', models.CharField(max_length=200, null=True, blank=True)),
                ('description', models.CharField(max_length=200, null=True, blank=True)),
                ('fontname', models.CharField(max_length=200, null=True, blank=True)),
                ('fontsize', models.CharField(max_length=200, null=True, blank=True)),
                ('fontcolor', models.CharField(max_length=200, null=True, blank=True)),
                ('fixedsize', models.BooleanField(default=False)),
                ('width', models.IntegerField(null=True, blank=True)),
                ('height', models.IntegerField(null=True, blank=True)),
                ('shape', models.CharField(max_length=200, null=True, blank=True)),
                ('style', models.CharField(max_length=200, null=True, blank=True)),
                ('fillcolor', models.CharField(max_length=200, null=True, blank=True)),
                ('gradientangle', models.CharField(max_length=200, null=True, blank=True)),
                ('color', models.CharField(max_length=200, null=True, blank=True)),
                ('imagePath', models.CharField(max_length=800, null=True, blank=True)),
                ('gvParams', models.CharField(max_length=800, null=True, blank=True)),
                ('smCreatedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smModifiedBy', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('smOwningTeam', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy')),
                ('smOwningUser', models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='sytle',
            field=models.ForeignKey(null=True, blank=True, to='rqGraph.NodeStyle'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node0',
            field=models.ForeignKey(null=True, blank=True, related_name='node0_set', to='rqGraph.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node1',
            field=models.ForeignKey(null=True, blank=True, related_name='node1_set', to='rqGraph.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='smCreatedBy',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edge',
            name='smModifiedBy',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edge',
            name='smOwningTeam',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='edge',
            name='smOwningUser',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edge',
            name='style',
            field=models.ForeignKey(null=True, blank=True, to='rqGraph.EdgeStyle'),
        ),
        migrations.AddField(
            model_name='clusternodes',
            name='node',
            field=models.ForeignKey(null=True, blank=True, to='rqGraph.Node'),
        ),
        migrations.AddField(
            model_name='clusternodes',
            name='smCreatedBy',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clusternodes',
            name='smModifiedBy',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clusternodes',
            name='smOwningTeam',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='clusternodes',
            name='smOwningUser',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvasdetail',
            name='cluster',
            field=models.ForeignKey(null=True, blank=True, to='rqGraph.Cluster'),
        ),
        migrations.AddField(
            model_name='canvasdetail',
            name='smCreatedBy',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvasdetail',
            name='smModifiedBy',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvasdetail',
            name='smOwningTeam',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to='protoLib.TeamHierarchy'),
        ),
        migrations.AddField(
            model_name='canvasdetail',
            name='smOwningUser',
            field=models.ForeignKey(null=True, editable=False, blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
